Add new events, reinvest and rebalance
VolumeFi/cellars pull request #11
Opened 2021-08-28 01:57 UTC by sandbochs

Initial PR that will add two new events to help track cellar TVL and fees collected in the subgraph.

```js
Reinvest & Rebalance
{
  fees0: uint256, // token 0 fees collected
  fees1: uint256, // token 1 fees collected
  amount0: uint256, // token 0 amount invested
  amount1: uint256 // token 1 amount invested
}
```

2021-08-28 02:01 UTC, sandbochs commented on contracts/CellarPoolShare.sol
> +        (inAmount0, inAmount1, , ) =
not sure if this is allowed? it was initialized in the previous `_addLiquidity` call

2021-08-30 01:27 UTC, webelf101 requested changes

2021-08-30 01:27 UTC, webelf101 commented on contracts/CellarPoolShare.sol
> +        totalInAmount1 += inAmount1
Semicolons are required at the end.

2021-08-30 01:27 UTC, webelf101 commented on contracts/CellarPoolShare.sol
> +        totalInAmount1 += inAmount1
Semicolons are required at the end.

2021-08-30 01:27 UTC, webelf101 commented on contracts/CellarPoolShare.sol
> +        emit Reinvest(fee0, fee1, investedAmount0, investedAmount1)
A semicolon is required at the end.

2021-08-30 01:27 UTC, webelf101 commented on contracts/CellarPoolShare.sol
> +        emit Rebalance(fee0, fee1, investedAmount0, investedAmount1)
A semicolon is required at the end.

2021-08-30 20:35 UTC, merged